---
- name: Ensure that kubectl is installed
  command: "which kubectl"
  register: kubectl_check
  changed_when: False
  failed_when: kubectl_check.rc != 0

- name: Check if StorageClass gp2 exists
  command: "kubectl get storageclass gp2"
  register: storageclass_check
  environment:
    KUBECONFIG: "/home/ansible-user/.kube/config"
  failed_when: storageclass_check.rc not in [0, 1]
  changed_when: False

- name: Debug storageclass.yaml.j2 path
  debug:
    msg: "Template file path: /home/ansible-user/singlenode/ansible/roles/ebs-csi-driver/templates/storageclass.yaml.j2"


- name: Check if storageclass.yaml exists on the remote server
  stat:
    path: /tmp/storageclass.yaml
  register: storageclass_check

- name: Remove existing /tmp/storageclass.yaml if it exists
  file:
    path: /tmp/storageclass.yaml
    state: absent
  ignore_errors: yes

- name: Copy StorageClass template to remote if it does not exist
  template:
    src: "{{ playbook_dir }}/roles/ebs-csi-driver/templates/storageclass.yaml.j2"
    dest: /tmp/storageclass.yaml
  when: storageclass_check.stat.exists == False
  environment:
    KUBECONFIG: /home/ansible-user/.kube/config


- name: Copy kubeconfig to remote
  copy:
    src: /home/ansible-user/.kube/config
    dest: /home/ansible-user/.kube/config
    mode: '0644'

- name: Debug storageclass_check stat.exists
  debug:
    msg: "storageclass_check.stat.exists: {{ storageclass_check.stat.exists }}"

- name: Apply StorageClass if it does not exist
  command:
    cmd: kubectl apply -f /tmp/storageclass.yaml
  environment:
    KUBECONFIG: /home/ansible-user/.kube/config
  when: storageclass_check.stat.exists == False

- name: Check if StorageClass exists
  command: kubectl get storageclass gp2 --kubeconfig /home/ansible-user/.kube/config
  register: storageclass_check
  failed_when: false
  changed_when: false

- name: Debug output of storageclass_check
  debug:
    var: storageclass_check

# Check if PersistentVolumeClaim ebs-pvc exists
- name: Check if persistentvolumeclaim.yaml exists on the remote node
  stat:
    path: /tmp/persistentvolumeclaim.yaml
  register: pvc_check

- name: Create PersistentVolumeClaim if it does not exist
  template:
    src: "templates/persistentvolumeclaim.yaml.j2"
    dest: /tmp/persistentvolumeclaim.yaml
  when: pvc_check.stat.exists == false
  environment:
    KUBECONFIG: /home/ansible-user/.kube/config

