apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodemaintenances.ops.k8s.io
spec:
  group: ops.k8s.io
  names:
    kind: NodeMaintenance
    listKind: NodeMaintenanceList
    plural: nodemaintenances
    singular: nodemaintenance
    shortNames:
      - nm
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["nodeName", "reason"]
              properties:
                nodeName:
                  type: string
                  description: "Name of the node to put into maintenance"
                reason:
                  type: string
                  description: "Reason for maintenance"
                startTime:
                  type: string
                  format: date-time
                  description: "When maintenance should start"
                duration:
                  type: string
                  description: "Expected duration of maintenance (e.g., 2h)"
                drain:
                  type: boolean
                  description: "Whether to drain the node"
                  default: true
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "InProgress", "Completed", "Failed"]
                lastUpdateTime:
                  type: string
                  format: date-time
                message:
                  type: string
