apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-maintenance-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-maintenance-controller
rules:
  - apiGroups: ["ops.k8s.io"]
    resources: ["nodemaintenances"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-maintenance-controller
subjects:
  - kind: ServiceAccount
    name: node-maintenance-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: node-maintenance-controller
  apiGroup: rbac.authorization.k8s.io
