
--- 
- name: Check if admin.conf already exists locally
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf_stat

- name: Fetch admin.conf from master if not already fetched
  fetch:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /tmp/admin.conf
    flat: yes
  when: not admin_conf_stat.stat.exists
  delegate_to: "{{ groups['master'][0] }}"

- name: Clean up temporary admin.conf on remote node
  delegate_to: master
  become: yes
  ansible.builtin.file:
    path: /tmp/admin.conf
    state: absent
  when: admin_conf_stat.stat.exists

