- name: Check if admin.conf exists on the master node
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf_stat
  delegate_to: "{{ groups['master'][0] }}"
  become: true

- name: Fetch admin.conf from master node if it exists
  fetch:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /tmp/admin.conf
    flat: yes
  when: admin_conf_stat.stat.exists
  delegate_to: "{{ groups['master'][0] }}"
  become: true

- name: Move admin.conf to the correct location on local machine
  command: mv /tmp/admin.conf /home/ansible-user/.kube/config
  when: admin_conf_stat.stat.exists
