- name: Set ownership and permissions of the config file
  file:
    path: /home/ansible-user/.kube/config
    owner: ansible-user
    group: ansible-user
    mode: "0644"
    state: file
  when: admin_conf_stat.stat.exists


