- name: Copy kubectl aliases to the nodes
  copy:
    src: kubectl_aliases.sh
    dest: /tmp/kubectl_aliases.sh
    owner: "{{ ansible_user | default(ansible_env.USER) }}"
    group: "{{ ansible_user | default(ansible_env.USER) }}"
    mode: "0644"

- name: Append kubectl aliases to .bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source /tmp/kubectl_aliases.sh"
    state: present

- name: Reload .bashrc to apply kubectl aliases for the current session
  shell: "source ~/.bashrc"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ ansible_user | default(ansible_env.USER) }}"
  # This ensures the aliases are sourced during the current session

- name: Source kubectl aliases for current session
  shell: source /tmp/kubectl_aliases.sh
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ ansible_user | default(ansible_env.USER) }}"
