---
- import_playbook: k8s-setup.yaml  hostlist=k8s_node
- import_playbook: helm-install.yaml hostlist=k8s_node
- import_playbook: time-sync.yaml  hostlist=k8s_node
- import_playbook: init-master.yml  hostlist=k8s_node
- import_playbook: first-master.yaml  hostlist=master
#- import_playbook: copy-admin-conf.yaml    hostlist=k8s_node
#- import_playbook: kubectl-local.yaml    hostlist=local
- import_playbook: kubectl_role.yaml hostlist=local
- import_playbook: configure_cni.yaml hostlist=k8s_node
- import_playbook: label-nodes.yaml hostlist=local
- import_playbook: join_worker_nodes.yaml hostlist=node
- import_playbook: argocd-install.yaml hostlist=master
- import_playbook: kubectl_alias.yaml hostlist=local
- import_playbook: label_controlplane.yaml hostlist=master
- import_playbook: aws_cloud_controller.yaml hostlist=node
- import_playbook: ingress-nginx.yaml hostlist=master
- import_playbook: k8s_cert_manager.yaml hostlist=master
- import_playbook: ingress-nginx.yaml hostlist=master
#- import_playbook: nfs.yaml hostlist=nfs
#- import_playbook: nfs-setup.yaml hostlist=master,node
#- import_playbook: ebs-csi-role.yaml hostlist=master
#- import_playbook: upgrade_k8s.yaml hostlist=master

