---
- name: Label control-plane nodes
  hosts: master
  tasks:
    - name: Get list of control-plane nodes
      shell: kubectl get nodes | grep control-plane | awk '{print $1}'
      register: control_plane_nodes
      changed_when: false

    - name: Debug control-plane nodes
      debug:
        msg: "Control-plane nodes found: {{ control_plane_nodes.stdout_lines }}"

    - name: Label each control-plane node
      shell: kubectl label node {{ item }} node-role.kubernetes.io/control-plane="" --overwrite
      loop: "{{ control_plane_nodes.stdout_lines }}"
      ignore_errors: true
